FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt
COPY llm /app/llm
COPY retrieval /app/retrieval
COPY eval /app/eval
COPY app /app/app
COPY movies_docs.json /app/movies_docs.json
EXPOSE 8000
CMD [ "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000" ]
