FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt
COPY ui /app/ui
COPY movies_docs.json /app/movies_docs.json
EXPOSE 8501
ENV API_URL=http://api:8000
ENV DOCS_PATH=/app/movies_docs.json
CMD [ "streamlit", "run", "ui/app.py", "--server.port=8501", "--server.address=0.0.0.0" ]
